### ISSUE TITLE
Deploy Chievments on Optimism.

### ISSUE THREAD

**Issue by 0xSero** [MetaFam/chievemints#10]
**Is your feature request related to a problem? Please describe.**

One of our grant milestones is deploying the chiev contracts on Optimsim

**Describe the solution you'd like**

Simple deployment, and swap out the cheiv network/address to OP on Metagame.wtf

https://app.charmverse.io/op-grants/page-27013511701775395

**Comment by Seroxdesign** [comment]
```

**Comment by dysbulic** [comment]
I deployed the contract to Optimism at [0xb77b8eDB779Cda90dBF651F8109857C97193CF9F](https://optimistic.etherscan.io/address/0xb77b8eDB779Cda90dBF651F8109857C97193CF9F). When trying to load the UI, however, the code works in development, but fails in production *(at [op.chiev.es](https://op.chiev.es))* with "`Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check`".

More debugging is needed…

**Comment by dysbulic** [comment]
Switching from Web3Modal to ConnectKit fixed the error & the Optimism site is deployed to [op.chiev.es](https://op.chiev.es).
